import re
import sys

from subprocess import Popen, PIPE
from typing import List

RE_IS_INCLUDE = re.compile(rb'^\s*#\s*include\b')
RE_RESULT = re.compile(rb'__RESULT\((.*?)\)RESULT__')

ACTION = sys.argv[1]
SEP_INDEX = sys.argv[2:].index('--')
CC_COMMAND = sys.argv[2:][:SEP_INDEX]
FILES = sys.argv[2:][SEP_INDEX + 1:]


def find_symbols(*wrapper_names: str) -> List[str]:
    args = map(lambda n: f'-D{n}(x)=__RESULT(x)RESULT__', wrapper_names)
    cmd = CC_COMMAND + ['-E'] + list(args) + ['-']
    symbols = []
    for path in FILES:
        with open(path, 'rb') as src:
            process = Popen(cmd, stdin=PIPE, stdout=PIPE)
            for line in src:
                if RE_IS_INCLUDE.match(line):
                    continue
                process.stdin.write(line)
            process.stdin.close()
            data = process.stdout.read()
            process.wait()
            symbols += [m.group(1) for m in RE_RESULT.finditer(data)]
    return [sym.decode() for sym in symbols]


if ACTION == '--map':
    symbols = find_symbols('WRAP_SYM', 'EXPORT_SYM')
    exported = ''.join(map(lambda s: ' "' + s + '";', symbols))
    sys.stdout.write("{\n  global:" + exported + "\n  local: *;\n};\n")
elif ACTION == '--ldscript':
    symbols = find_symbols('WRAP_SYM')
    lines = map(lambda s: f'{s} = ip2unix_wrap_{s};', symbols)
    sys.stdout.write("\n".join(lines) + "\n")
elif ACTION == '--interpose':
    # Darwin: ld64 has no linker scripts, so instead of aliasing symbols at
    # link time we emit dyld interpose tuples (__DATA,__interpose), which
    # dyld applies when the library is loaded via DYLD_INSERT_LIBRARIES.
    symbols = find_symbols('WRAP_SYM')
    out = [
        '// Generated by gensyms.py --interpose',
        'struct Ip2UnixInterpose {',
        '    const void *replacement;',
        '    const void *replacee;',
        '};',
        '',
    ]
    for sym in symbols:
        out += [
            f'extern "C" void ip2unix_wrap_{sym}(void);',
            f'extern "C" void {sym}(void);',
            '__attribute__((used, section("__DATA,__interpose")))',
            f'static const Ip2UnixInterpose ip2unix_interpose_{sym} = {{',
            f'    reinterpret_cast<const void *>(&ip2unix_wrap_{sym}),',
            f'    reinterpret_cast<const void *>(&{sym})}};',
            '',
        ]
    sys.stdout.write("\n".join(out))
